"""add indexes

Revision ID: 33edf1d1d924
Revises: 6059a86142ac
Create Date: 2020-11-05 15:48:05.166130

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "33edf1d1d924"
down_revision = "6059a86142ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_encounter_location_uuid"), "encounter", ["location_uuid"], unique=False
    )
    op.create_index(
        op.f("ix_encounter_parent_uuid"), "encounter", ["parent_uuid"], unique=False
    )
    op.create_index(
        op.f("ix_encounter_patient_uuid"), "encounter", ["patient_uuid"], unique=False
    )
    op.create_index(
        op.f("ix_location_history_arrived_at"),
        "location_history",
        ["arrived_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_location_history_location_uuid"),
        "location_history",
        ["location_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_score_system_history_encounter_uuid"),
        "score_system_history",
        ["encounter_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_score_system_history_encounter_uuid"),
        table_name="score_system_history",
    )
    op.drop_index(
        op.f("ix_location_history_location_uuid"), table_name="location_history"
    )
    op.drop_index(op.f("ix_location_history_arrived_at"), table_name="location_history")
    op.drop_index(op.f("ix_encounter_patient_uuid"), table_name="encounter")
    op.drop_index(op.f("ix_encounter_parent_uuid"), table_name="encounter")
    op.drop_index(op.f("ix_encounter_location_uuid"), table_name="encounter")
    # ### end Alembic commands ###
