"""Initial migration

Revision ID: d6b859f01555
Revises: 
Create Date: 2020-07-24 10:25:02.335519

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d6b859f01555"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "encounter",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("epr_encounter_id", sa.String(), nullable=True),
        sa.Column("encounter_type", sa.String(), nullable=True),
        sa.Column("admitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("discharged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("spo2_scale", sa.Integer(), nullable=True),
        sa.Column("location_uuid", sa.String(length=36), nullable=False),
        sa.Column("dh_product_uuid", sa.String(length=36), nullable=False),
        sa.Column("patient_record_uuid", sa.String(length=36), nullable=False),
        sa.Column("patient_uuid", sa.String(length=36), nullable=False),
        sa.Column("parent_uuid", sa.String(), nullable=True),
        sa.Column("score_system", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_uuid"],
            ["encounter.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "location_history",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("encounter_uuid", sa.String(), nullable=True),
        sa.Column("location_uuid", sa.String(length=36), nullable=False),
        sa.Column("arrived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("departed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["encounter_uuid"],
            ["encounter.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "score_system_history",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("encounter_uuid", sa.String(), nullable=True),
        sa.Column("score_system", sa.String(), nullable=True),
        sa.Column("previous_score_system", sa.String(), nullable=True),
        sa.Column("spo2_scale", sa.Integer(), nullable=True),
        sa.Column("previous_spo2_scale", sa.Integer(), nullable=True),
        sa.Column("changed_by", sa.String(), nullable=True),
        sa.Column("clinician_uuid", sa.String(length=36), nullable=True),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["encounter_uuid"],
            ["encounter.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(
        "epr_encounter_id_deleted_at",
        "encounter",
        [
            "epr_encounter_id",
            sa.text(
                "COALESCE(deleted_at, '1970-01-01 00:00:00+00'::timestamp with time zone)"
            ),
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("score_system_history")
    op.drop_table("location_history")
    op.drop_table("encounter")
    # ### end Alembic commands ###
