"""Added merge_history

Revision ID: db9023dbf02a
Revises: d6b859f01555
Create Date: 2020-07-24 16:01:08.199016

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "db9023dbf02a"
down_revision = "d6b859f01555"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("encounter", sa.Column("merge_history", sa.JSON(), nullable=True))
    op.create_unique_constraint(None, "encounter", ["uuid"])
    op.alter_column(
        "location_history", "encounter_uuid", existing_type=sa.VARCHAR(), nullable=False
    )
    op.create_unique_constraint(None, "location_history", ["uuid"])
    op.create_unique_constraint(None, "score_system_history", ["uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "score_system_history", type_="unique")
    op.drop_constraint(None, "location_history", type_="unique")
    op.alter_column(
        "location_history", "encounter_uuid", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_constraint(None, "encounter", type_="unique")
    op.drop_column("encounter", "merge_history")
    # ### end Alembic commands ###
