@startuml

skinparam defaultFontName Courier

Class Encounter {
    VARCHAR[36]                        ★ uuid                       
    VARCHAR                            ☆ parent_uuid                
    DATETIME                           ⚪ admitted_at                
    DATETIME                           ⚪ created                    
    VARCHAR                            ⚪ created_by_                
    DATETIME                           ⚪ deleted_at                 
    VARCHAR[36]                        ⚪ dh_product_uuid            
    DATETIME                           ⚪ discharged_at              
    VARCHAR                            ⚪ encounter_type             
    VARCHAR                            ⚪ epr_encounter_id           
    VARCHAR[36]                        ⚪ location_uuid              
    JSON                               ⚪ merge_history              
    DATETIME                           ⚪ modified                   
    VARCHAR                            ⚪ modified_by_               
    VARCHAR[36]                        ⚪ patient_record_uuid        
    VARCHAR[36]                        ⚪ patient_uuid               
    VARCHAR                            ⚪ score_system               
    INTEGER                            ⚪ spo2_scale                 
    +                                  location_history             
    +                                  score_system_history         
    remove()                                                        
    to_dict()                                                       
    update()                                                        
    INDEX[epr_encounter_id,deleted_at] » epr_encounter_id_deleted_at
    INDEX[location_uuid]               » ix_encounter_location_uuid 
    INDEX[parent_uuid]                 » ix_encounter_parent_uuid   
    INDEX[patient_uuid]                » ix_encounter_patient_uuid  
}

Class LocationHistory {
    VARCHAR[36]          ★ uuid                             
    VARCHAR              ☆ encounter_uuid                   
    DATETIME             ⚪ arrived_at                       
    DATETIME             ⚪ created                          
    VARCHAR              ⚪ created_by_                      
    DATETIME             ⚪ departed_at                      
    VARCHAR[36]          ⚪ location_uuid                    
    DATETIME             ⚪ modified                         
    VARCHAR              ⚪ modified_by_                     
    +                    encounter                          
    to_dict()                                               
    INDEX[arrived_at]    » ix_location_history_arrived_at   
    INDEX[location_uuid] » ix_location_history_location_uuid
}

Class ScoreSystemHistory {
    VARCHAR[36]           ★ uuid                                  
    VARCHAR               ☆ encounter_uuid                        
    DATETIME              ⚪ changed_time                          
    DATETIME              ⚪ created                               
    VARCHAR               ⚪ created_by_                           
    DATETIME              ⚪ modified                              
    VARCHAR               ⚪ modified_by_                          
    VARCHAR               ⚪ previous_score_system                 
    INTEGER               ⚪ previous_spo2_scale                   
    VARCHAR               ⚪ score_system                          
    INTEGER               ⚪ spo2_scale                            
    to_dict()                                                     
    update()                                                      
    INDEX[encounter_uuid] » ix_score_system_history_encounter_uuid
}

Encounter <--o Encounter: parent_uuid

LocationHistory <--o Encounter: encounter_uuid

ScoreSystemHistory <--o Encounter: encounter_uuid

right footer generated by sadisplay v0.4.9

@enduml
